### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by KasaiKonoru** [discord/embedded-app-sdk#43]
ReferenceError: window is not defined
at Object.<anonymous> (/root/01-FILES/discord-bots/zipfelbanane/node_modules/@discord/embedded-app-sdk/output/Discord.cjs:25:5)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at Module.load (node:internal/modules/cjs/loader:1117:32)
at Module._load (node:internal/modules/cjs/loader:958:12)
at Module.require (node:internal/modules/cjs/loader:1141:19)
at Hook._require.Module.require (/root/.nvm/versions/node/v20.11.1/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
at require (node:internal/modules/cjs/helpers:110:18)
at Object.<anonymous> (/root/01-FILES/discord-bots/zipfelbanane/node_modules/@discord/embedded-app-sdk/output/index.cjs:3:15)
at Module._compile (node:internal/modules/cjs/loader:1254:14)

**Comment by matthova** [comment]
The SDK is meant to be run in a browser, however sometimes with server-side-rendering a non-browser environment may error out when referencing `window` and other browser-related global variables. We've addressed the issue of server-side-rendering with the latest version of the sdk, however, outside of server-side-rendering, the sdk is not meant to be run outside of a browser.

To use the latest version of the sdk run the following
```
npm install @discord/embedded-app-sdk@latest
```

**Comment by KasaiKonoru** [comment]
thx
